spring:
  application:
    name: @project.artifactId@
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: false
  vaadin:
    productionMode: false

server:
  port: 42022
  servlet:
    contextPath: null

logging:
  file: logs/upo.log
---

spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:changelog/changelog.xml
    default-schema: upo

---

spring:
  profiles: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:upo;INIT=CREATE SCHEMA IF NOT EXISTS UPO
    username: upo
    password: upo
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    show_sql: true
  h2:
    console:
      enabled: true
      path: /h2

  liquibase:
    contexts: production,test
    drop-first: true

---

spring:
  profiles: local
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost\SQLEXPRESS;database=upo-local
    username: upo
    password: upo
    hikari:
      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    database: sql_server
    show_sql: true

  liquibase:
    contexts: production,test

---

spring:
  profiles: production
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost\SQLEXPRESS;database=upo
    username: upo
    password: J2edTHyq
    hikari:
      maximum-pool-size: 20
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    database: sql_server
    show_sql: false

  liquibase:
    contexts: production

  vaadin:
    productionMode: true