server:
  port: 8081
  servlet:
    contextPath: /upo
---
spring:
  profiles: production
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost\SQLEXPRESS;database=upo
    username: upo-prod
    password: J2edTHyq
    hikari:
      maximum-pool-size: 20
      schema: upo
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    database: sql_server
    show_sql: false

  liquibase:
    contexts: production
    default-schema: upo
    liquibase-schema: upo

  vaadin:
    productionMode: true